apiVersion: v2
name: kotoba
description: A Helm chart for Kotoba distributed graph database
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - graph
  - database
  - distributed
  - gke
  - kubernetes
home: https://github.com/com-junkawasaki/kotoba
sources:
  - https://github.com/com-junkawasaki/kotoba
maintainers:
  - name: Jun Kawasaki
    email: jun784@example.com
