apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kotoba-storage-template
  namespace: kotoba-system
  labels:
    app: kotoba
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwo  # GKE standard persistent disk
