[package]
name = "kotoba-graph-api"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "REST API for Kotoba Graph Database operations"
keywords = ["api", "rest", "graph", "database", "crud"]
categories = ["web-programming", "api-bindings", "database"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-graph-api"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling and logging
anyhow = "1.0"
tracing = "0.1"

# Kotoba crates
kotoba-core = { path = "../../000-core/kotoba-core", version = "0.1.22" }
kotoba-graphdb = { path = "../../100-storage/kotoba-graphdb", version = "0.1.22" }
kotoba-errors = "0.1.2"

# Additional utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tower = { version = "0.4", features = ["util"] }
reqwest = { version = "0.11", features = ["json"] }
tempfile = "3.0"
