[package]
name = "kotoba-routing"
version = "0.1.0"
edition = "2021"
description = "Declarative, graph-based HTTP routing engine for the Kotoba ecosystem."
authors = ["jun784"]
license = "MIT OR Apache-2.0"

[dependencies]
# Simplified dependencies - removed problematic workflow/jsonnet deps
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
