[package]
name = "kotoba-routing"
version = "0.1.16"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Declarative, graph-based HTTP routing engine for the Kotoba ecosystem."
keywords = ["routing", "http", "graph", "web", "middleware"]
categories = ["web-programming", "data-structures"]
documentation = "https://docs.rs/kotoba-routing"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Simplified dependencies - removed problematic workflow/jsonnet deps
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
