[package]
name = "kotoba-routing"
version = "0.1.0"
edition = "2021"
description = "Declarative, graph-based HTTP routing engine for the Kotoba ecosystem."
authors = ["jun784"]
license = "MIT OR Apache-2.0"

[dependencies]
# This will be linked within the kotoba workspace
kotoba-workflow = { path = "../kotoba-workflow" }
kotoba-jsonnet = { path = "../kotoba-jsonnet" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
