[package]
name = "kotoba-deploy"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Deployment and hosting system for Kotoba applications with global distribution and auto-scaling"
keywords = ["deployment", "hosting", "scaling", "cloud", "distributed"]
categories = ["web-programming", "network-programming"]
documentation = "https://docs.rs/kotoba-deploy"
homepage = "https://github.com/com-junkawasaki/kotoba"

[lib]
name = "kotoba_deploy"
path = "src/lib.rs"

[dependencies]
# Kotoba internal crates - Port layer
kotoba-core = { path = "../../000-core/kotoba-core", version = "0.1.22" }
kotoba-errors = { path = "../../000-core/kotoba-errors", version = "0.1.2" }
kotoba-storage = { path = "../../100-storage/kotoba-storage", version = "0.1.22" }
kotoba-execution = { path = "../../200-application/kotoba-execution", version = "0.1.22" }
kotoba-rewrite = { path = "../../200-application/kotoba-rewrite", version = "0.1.22" }
# kotoba-graph temporarily disabled - will be replaced with KeyValueStore
# kotoba-kotobas.workspace = true  # Optional for now due to stability

# External dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
tokio = { version = "1.0", features = ["full"] }
regex = "1.0"
tempfile = "3.0"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"
sha2 = { version = "0.10", features = ["std"] }
hex = "0.4"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
