[package]
name = "kotoba-security"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Comprehensive authentication and authorization system with JWT, OAuth2, MFA"
keywords = ["security", "jwt", "oauth2", "authentication", "authorization"]
categories = ["authentication", "cryptography", "web-programming", "api-bindings"]
documentation = "https://docs.rs/kotoba-security"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# JWT and cryptography
jsonwebtoken = "7.0"
ring = "0.16"
rustls = "0.20"
rustls-pemfile = "0.3"
hex = { workspace = true }
sha2 = { workspace = true }

# OAuth2
oauth2 = "4.2"
openidconnect = "2.0"
url = "2.4"

# Password hashing
argon2 = "0.5"
pbkdf2 = { version = "0.12", features = ["simple"] }
bcrypt = "0.15"
password-hash = "0.5"

# MFA/TOTP
totp-rs = "5.0"
qrcode = { version = "0.12", features = ["svg"] }

# HTTP client for OAuth2
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# Time utilities
chrono = { version = "0.4", features = ["serde"] }

# Random generation
rand = "0.8"
uuid = { version = "1.0", features = ["v4", "serde"] }

# HMAC for PBKDF2
hmac = "0.12.1"
digest = "0.10.7"

# Regular expressions for ABAC conditions
regex = "1.10"

# Kotoba dependencies
kotoba-graph = { path = "../kotoba-graph", version = "0.1.17" }
kotoba-storage = { path = "../kotoba-storage", version = "0.1.16" }

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.2"
