[workspace]
members = [
    "crates/*",
    ".",  # Root crate
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jun784/kotoba"

[workspace.dependencies]
# Common dependencies can be defined here
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
uuid = { version = "1.18", features = ["v4", "serde"] }
sha2 = "0.10"
hex = "0.4"
parking_lot = "0.12"
regex = "1.10"

# Root crate configuration
[package]
name = "kotoba"
version = "0.1.2"
edition = "2021"
description = "GP2-based Graph Rewriting Language - ISO GQL-compliant queries, MVCC+Merkle persistence, and distributed execution"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jun784/kotoba"
keywords = ["graph", "database", "gql", "rewrite", "distributed"]
categories = ["database", "data-structures", "algorithms"]
authors = ["Jun Kawasaki <jun784@example.com>"]
readme = "README.md"
documentation = "https://docs.rs/kotoba"
homepage = "https://github.com/jun784/kotoba"
exclude = ["examples/**/*", "benches/**/*", "tests/**/*", "src/topology.rs", "src/bin/**/*"]

[dependencies]
# Core crates - published versions
kotoba-core = "0.1.1"
kotoba-graph = "0.1.1"
kotoba-storage = "0.1.1"
kotoba-execution = "0.1.1"
kotoba-rewrite = "0.1.1"
# kotoba-security = "0.1.0" # まだ安定していないためコメントアウト
# kotoba-web = "0.1.1" # オプション機能のためコメントアウト

# For binary
clap = { version = "4.0", features = ["derive"], optional = true }

# Optional crates for different use cases
tokio = { version = "1.0", features = ["full"], optional = true }
log = { version = "0.4", optional = true }
env_logger = { version = "0.11", optional = true }
uuid = { version = "1.0", features = ["v4"] }

[features]
default = ["full"]
full = ["tokio", "log", "env_logger", "examples", "binary"]
binary = ["clap"]
examples = []
types = []
ir = []
graph = []
storage = []
execution = []
planner = []
rewrite = []
http = []
frontend = []
wasm = []

# Platform-specific features
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"
quickcheck = "1.0"
rand = "0.8"
uuid = { version = "1.0", features = ["v4"] }

[[bench]]
name = "graph_operations"
harness = false

[[bench]]
name = "query_execution"
harness = false

[[bench]]
name = "rewrite_operations"
harness = false

[[bench]]
name = "storage_operations"
harness = false

# Examples are excluded from publish to avoid dependency issues
# [[example]]
# name = "http_server"
# path = "examples/http_server/main.rs"

# [[example]]
# name = "tauri_react_app"
# path = "examples/tauri_react_app/src-tauri/src/main.rs"
