[workspace]
members = [
    "crates/*",
    ".",  # Root crate
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jun784/kotoba"

[workspace.dependencies]
# Common dependencies can be defined here
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"

# Root crate configuration
[package]
name = "kotoba"
version = "0.1.0"
edition = "2021"
description = "GP2-based Graph Rewriting Language - ISO GQL-compliant queries, MVCC+Merkle persistence, and distributed execution"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jun784/kotoba"
keywords = ["graph", "database", "gql", "rewrite", "distributed"]
categories = ["database", "data-structures", "algorithms"]
authors = ["Jun Kawasaki <jun784@example.com>"]
readme = "README.md"
documentation = "https://docs.rs/kotoba"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
# Core crates - published versions
kotoba-core = "0.1.0"
kotoba-graph = "0.1.0"
kotoba-storage = "0.1.0"
kotoba-execution = "0.1.0"
kotoba-rewrite = "0.1.0"
# kotoba-web = { version = "0.1.0", optional = true } # まだpublishされていないため一時的にコメントアウト

# Optional crates for different use cases
tokio = { version = "1.0", features = ["full"], optional = true }
log = { version = "0.4", optional = true }
env_logger = { version = "0.11", optional = true }

[features]
default = ["full"]
full = ["tokio", "log", "env_logger", "examples"]
examples = []
types = []
ir = []
graph = []
storage = []
execution = []
planner = []
rewrite = []
http = []
frontend = []
wasm = []

# Platform-specific features
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"
quickcheck = "1.0"
rand = "0.8"

[[bench]]
name = "graph_operations"
harness = false

[[bench]]
name = "query_execution"
harness = false

[[bench]]
name = "rewrite_operations"
harness = false

[[bench]]
name = "storage_operations"
harness = false

[[example]]
name = "http_server"
path = "examples/http_server/main.rs"

[[example]]
name = "tauri_react_app"
path = "examples/tauri_react_app/src-tauri/src/main.rs"
