[package]
name = "kotoba"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
sha2 = "0.10"
thiserror = "2.0"
tokio = { version = "1.0", features = ["full"] }
parking_lot = "0.12"
dashmap = "6.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
