[package]
name = "kotoba"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
sha2 = "0.10"
thiserror = "2.0"
tokio = { version = "1.0", features = ["full"] }
parking_lot = "0.12"
dashmap = "6.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"

[features]
default = ["types", "ir", "graph"]
full = ["types", "ir", "graph", "storage", "execution", "planner", "rewrite"]
examples = ["full"]
types = []
ir = ["types"]
graph = ["types", "ir"]
storage = ["types", "graph"]
execution = ["types", "ir", "graph", "storage"]
planner = ["types", "ir", "graph"]
rewrite = ["types", "ir", "graph", "storage"]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"
quickcheck = "1.0"
rand = "0.8"

[[bench]]
name = "graph_operations"
harness = false

[[bench]]
name = "query_execution"
harness = false

[[bench]]
name = "rewrite_operations"
harness = false

[[bench]]
name = "storage_operations"
harness = false

[[example]]
name = "social_network"
path = "examples/social_network/main.rs"
