[package]
name = "vm_cpu"
version = "0.1.0"
edition = "2021"
description = "Von Neumann CPU core implementation for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "vm_cpu"
path = "src/lib.rs"

[dependencies]
vm_types = { path = "../vm-types" }
vm_memory = { path = "../vm-memory" }
