[package]
name = "kotoba-schema-registry"
version = "0.1.21"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Schema registry for managing and evolving JSON schemas in Kotoba ecosystem"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonschema = "0.17"
thiserror = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
url = { version = "2.2", features = ["serde"] }

kotoba-schema = "0.1.21"
