[package]
name = "kotoba-errors"
version = "0.1.1"
edition = "2021"
description = "Shared error types for the Kotoba ecosystem."
license = "Apache-2.0"

[dependencies]
thiserror = "1.0"
serde_json = "1.0"
anyhow = "1.0"
# We might need other error types from other crates here in the future
