[package]
name = "kotoba-cli"
version = "0.1.22"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for the Kotoba language toolchain"

[dependencies]
kotoba-language = { path = "../../020-language/030-kotoba-language" }
clap = { version = "4.0", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
