[package]
name = "kotoba-query-engine"
version = "0.1.0"
edition = "2021"
description = "ISO GQL query engine for KotobaDB"
license = "MIT OR Apache-2.0"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Parser
pest = "2.0"
pest_derive = "2.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Collections
itertools = "0.12"

# Regex for pattern matching
regex = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Futures for async streams
futures = "0.3"

# Kotoba dependencies - Port layer
kotoba-storage = { path = "../../100-storage/kotoba-storage" }
kotoba-core = { path = "../../000-core/kotoba-core" }
kotoba-errors = { path = "../../000-core/kotoba-errors" }
# kotoba-event-stream = { path = "../../200-application/kotoba-event-stream" }
