{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kotoba.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kotoba.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kotoba.selectorLabels" . | nindent 6 }}
      component: storage
{{- end }}
