[package]
name = "kotoba-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Temporal-inspired workflow engine for Kotoba"

[dependencies]
# Kotoba crates - only core types for now to avoid RocksDB dependency
kotoba-core = { workspace = true }

# Common dependencies
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
thiserror.workspace = true
anyhow.workspace = true

# Additional dependencies for workflow engine
async-trait = "0.1"
futures = { workspace = true }
parking_lot.workspace = true

# Optional storage backends
rocksdb = { version = "0.21", optional = true }
rusqlite = { version = "0.29", features = ["bundled"], optional = true }

# Kotoba dependencies for integration
kotoba-jsonnet = { workspace = true }

[features]
default = ["memory"]
memory = []
rocksdb = ["dep:rocksdb"]
sqlite = ["dep:rusqlite"]

[dev-dependencies]
tempfile.workspace = true
