[package]
name = "kotoba-workflow"
version = "0.1.16"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Temporal-inspired workflow engine for Kotoba"

[dependencies]
# Kotoba crates - only core types for now to avoid RocksDB dependency
kotoba-core = { path = "../kotoba-core", version = "0.1.19" }
kotoba-errors = { path = "../kotoba-errors", version = "0.1.1" }

# Common dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
thiserror = "2.0"
anyhow = "1.0"

# Additional dependencies for workflow engine
async-trait = "0.1"
futures = "0.3"
parking_lot = "0.12"

# HTTP client for activities
reqwest = { version = "0.11", features = ["json"], optional = true }

# Database clients for activities
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"], optional = true }
lapin = { version = "2.0", optional = true }

# Optional storage backends
rocksdb = { version = "0.21", optional = true }
rusqlite = { version = "0.29", features = ["bundled"], optional = true }

# Kotoba dependencies for integration
kotoba-jsonnet = { workspace = true }
kotoba-storage = { workspace = true }

[features]
default = ["memory"]
memory = []
rocksdb = ["dep:rocksdb"]
sqlite = ["dep:rusqlite"]
activities-http = ["dep:reqwest"]
activities-db = ["dep:sqlx", "dep:lapin"]

[dev-dependencies]
tempfile.workspace = true
