[workspace]
resolver = "2" # Use the edition 2021 resolver
members = [
    "crates/vm-benchmarks",
    "crates/vm-cli",
    "crates/vm-core",
    "crates/vm-cpu",
    "crates/vm-hardware",
    "crates/vm-memory",
    "crates/vm-scheduler",
    "crates/vm-types",
    "crates/vm-gnn",
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3

[workspace.dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
twox-hash = "1.6"
rayon = "1.8"
tokio = { version = "1.0", features = ["full"] }
