[package]
name = "vm-cli"
version = "0.1.1"
edition = "2021"
description = "Command-line interface for the Digital Computing System VM"
license = "Apache-2.0"

[[bin]]
name = "vm-cli"
path = "src/main.rs"

[dependencies]
vm_core = { path = "../vm-core" }
vm_types = { path = "../vm-types" }
vm_memory = { path = "../vm-memory" }
vm_cpu = { path = "../vm-cpu" }
vm_scheduler = { path = "../vm-scheduler" }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
