[package]
name = "kotoba2tsx"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Complete toolchain for converting Kotoba configuration files to React TypeScript components"
keywords = ["react", "tsx", "converter", "jsonnet", "frontend"]
categories = ["command-line-utilities", "web-programming", "development-tools"]
documentation = "https://docs.rs/kotoba2tsx"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Kotoba ecosystem
kotoba-graph-core = { path = "../../010-core/016-kotoba-graph-core" }
kotoba-kotobas = { path = "../023-kotoba-kotobas" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"], optional = true }
tokio = { version = "1.0", features = ["full"] }
regex = "1.10"
jsonnet-rs = "0.17"
uuid = { workspace = true, features = ["v4"] }
parking_lot = "0.12"
hex = { workspace = true }
sha2 = { workspace = true }

# Additional dependencies for enhanced functionality
indexmap = "2.0"

[features]
default = ["std", "cli"]
std = []
cli = ["clap"]
wasm = ["wasm-bindgen", "web-sys", "js-sys"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
