# Kotoba Test Runner Configuration

[test]
# タイムアウト時間（秒）
timeout = 30

# 並列実行数
concurrency = 4

# フィルター
filter = "user"

# 詳細出力
verbose = true

# カバレッジ収集
coverage = true

# 除外ファイルパターン
exclude_patterns = [
    "node_modules",
    ".git",
    "target",
    "build"
]
