[package]
name = "kotoba-vm-hardware"
version = "0.1.0"
edition = "2021"
description = "Heterogeneous hardware tile simulation for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "kotoba_vm_hardware"
path = "src/lib.rs"

[dependencies]
kotoba-vm-types = { path = "../kotoba-vm-types" }
