[package]
name = "kotoba-db-cluster"
version = "0.1.21"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Distributed clustering and consensus for KotobaDB"
keywords = ["database", "distributed", "clustering", "consensus", "raft"]
categories = ["database-implementations", "network-programming"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-db-cluster"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
serde = { workspace = true, features = ['derive'] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
uuid = { version = "1.0", features = ["v4"] }
parking_lot = "0.12"
futures = "0.3"
rand = "0.8"
dashmap = "5.5"

# Build dependencies
[build-dependencies]
tonic-build = "0.9"

# KotobaDB dependencies
# kotoba-db-core temporarily disabled - will be replaced with kotoba-storage
# kotoba-db = { path = "../../200-application/kotoba-graphdb", version = "0.1.21", optional = true }

[features]
default = []
full = ["kotoba-db"]

[[bin]]
name = "kotoba-cluster"
path = "src/bin/main.rs"
required-features = ["full"]
