[package]
name = "kotoba-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Complete HTTP server and frontend integration system for Kotoba graph database"
keywords = ["server", "http", "graphql", "websocket", "frontend", "api"]
categories = ["web-programming", "api-bindings", "asynchronous"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-server"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio.workspace = true
hyper = { version = "0.14", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["full"] }
uuid.workspace = true
parking_lot.workspace = true
hex.workspace = true
sha2.workspace = true
tempfile.workspace = true
kotoba-core = { path = "../kotoba-core" }
kotoba-schema = { path = "../kotoba-schema" }
kotoba-graph = { path = "../kotoba-graph" }
kotoba-storage = { path = "../kotoba-storage" }
kotoba-execution = { path = "../kotoba-execution" }
kotoba-rewrite = { path = "../kotoba-rewrite" }
kotoba-security = { path = "../kotoba-security" }

# GraphQL support
async-graphql = { version = "6.0", features = ["dynamic-schema", "apollo_tracing"] }
graphql-parser = "0.4"

[features]
default = ["std"]
std = []
wasm = ["wasm-bindgen", "web-sys", "js-sys"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
