[package]
name = "kotoba-server"
version = "0.1.21"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Complete HTTP server and frontend integration system for Kotoba graph database"
keywords = ["server", "http", "graphql", "websocket", "api"]
categories = ["web-programming", "api-bindings", "asynchronous"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-server"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Web framework
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5", features = ["trace", "cors"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling and logging
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# CLI argument parsing
clap = { version = "4.0", features = ["derive"] }

# Kotoba crates
kotoba-core = "0.1.21"
kotoba-routing = "0.1.16"
kotoba-errors = "0.1.2"
kotoba-workflow = { path = "../kotoba-workflow", version = "0.1.16" }
uuid = { version = "1.0", features = ["v4", "serde"] }

# GraphQL support
async-graphql = { version = "6.0", features = ["dynamic-schema", "apollo_tracing"] }
graphql-parser = "0.4"

[features]
default = ["std"]
std = []
wasm = ["wasm-bindgen", "web-sys", "js-sys"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
