[package]
name = "kotoba-server"
version = "0.1.16"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Complete HTTP server and frontend integration system for Kotoba graph database"
keywords = ["server", "http", "graphql", "websocket", "api"]
categories = ["web-programming", "api-bindings", "asynchronous"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-server"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
parking_lot = "0.12"
hex = "0.4"
sha2 = { version = "0.10", features = ["std"] }
kotoba-core = { path = "../kotoba-core", version = "0.1.19" }
kotoba-schema = { path = "../kotoba-schema", version = "0.1.16" }

# GraphQL support
async-graphql = { version = "6.0", features = ["dynamic-schema", "apollo_tracing"] }
graphql-parser = "0.4"

[features]
default = ["std"]
std = []
wasm = ["wasm-bindgen", "web-sys", "js-sys"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
