[package]
name = "kotoba-monitoring"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Comprehensive monitoring and metrics collection system for KotobaDB"
keywords = ["monitoring", "metrics", "prometheus", "health-check", "observability"]
categories = ["development-tools::profiling", "database-implementations"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-monitoring"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde = { workspace = true, features = ['derive'] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
chrono = { workspace = true, features = ["serde"] }
futures = "0.3"
parking_lot = "0.12"
uuid = { workspace = true, features = ["v4"] }
regex = "1.0"
lazy_static = "1.4"

# Metrics collection
metrics = "0.23"
metrics-exporter-prometheus = "0.15"

# HTTP server for metrics endpoint
axum = "0.6"
tower = "0.4"
tower-http = "0.4"

# Optional advanced monitoring
sysinfo = { version = "0.30", optional = true }

# KotobaDB dependencies
kotoba-db = { path = "../kotoba-db", version = "0.1.0" }
kotoba-db-cluster = { path = "../kotoba-db-cluster", version = "0.1.0", optional = true }

[features]
default = []
cluster = ["kotoba-db-cluster"]
system = ["sysinfo"]

[dev-dependencies]
tokio-test = "0.4"
