[package]
name = "vm_core"
version = "0.1.0"
edition = "2021"
description = "Core VM integration layer for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "vm_core"
path = "src/lib.rs"

[dependencies]
vm_types = { path = "../vm-types" }
vm_memory = { path = "../vm-memory" }
vm_cpu = { path = "../vm-cpu" }
vm_scheduler = { path = "../vm-scheduler" }
vm_hardware = { path = "../vm-hardware" }
vm-gnn = { path = "../vm-gnn" }
serde_json = "1.0"
tokio = { workspace = true }
