[package]
name = "kotoba-storage-rocksdb"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "RocksDB adapter for kotoba-storage port"
keywords = ["rocksdb", "storage", "adapter", "database"]
categories = ["database-implementations"]

[dependencies]
# Port layer
kotoba-storage = { path = "../kotoba-storage" }

# External dependencies
rocksdb = "0.21"
anyhow = "1.0"
async-trait = "0.1"
