[package]
name = "kotoba-storage-rocksdb"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "RocksDB adapter for kotoba-storage port"
keywords = ["rocksdb", "storage", "adapter", "database"]
categories = ["database-implementations"]

[dependencies]
# Port layer
kotoba-storage = "0.1.22"

# External dependencies
rocksdb = "0.21"
anyhow = "1.0"
async-trait = "0.1"

[dev-dependencies]
tempfile = "3.0"
tokio = { version = "1.0", features = ["full"] }
