[package]
name = "kotoba-workflow"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Serverless Workflow specification compliant workflow engine"

[dependencies]
# Kotoba crates - core workflow functionality
kotoba-core = { path = "../../000-core/kotoba-core", version = "0.1.22" }
kotoba-errors = "0.1.2"
# kotoba-workflow-core = { path = "../kotoba-workflow-core", version = "0.1.22" }
# kotoba-routing = { version = "0.1.22", optional = true }

# Common dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
thiserror = "2.0"
anyhow = "1.0"

# Additional dependencies for workflow engine
async-trait = "0.1"
futures = "0.3"
parking_lot = "0.12"

# HTTP client for activities
reqwest = { version = "0.11", features = ["json"], optional = true }

# Database clients for activities
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres"], optional = true }
lapin = { version = "2.0", optional = true }
redis = { version = "0.23", optional = true }

# Optional storage backends
rocksdb = { version = "0.21", optional = true }
rusqlite = { version = "0.29", features = ["bundled"], optional = true }

# Kotoba dependencies for integration
kotoba-jsonnet = { version = "0.1.22", optional = true }
kotoba-storage = { version = "0.1.22", optional = true }

[features]
default = ["memory", "kotoba-storage", "kotoba-jsonnet"]
memory = []
rocksdb = ["dep:rocksdb"]
sqlite = ["dep:rusqlite"]
activities-http = ["dep:reqwest"]
activities-db = ["dep:sqlx", "dep:lapin", "dep:redis"]
kotoba-storage = ["dep:kotoba-storage"]
kotoba-jsonnet = ["dep:kotoba-jsonnet"]
# kotoba-routing = ["dep:kotoba-routing"]

# Feature for WASM builds
wasm-bindgen = ["uuid/js"]

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# tokio = { version = "1.0", default-features = false, features = ["rt", "macros", "sync", "time"] }
# # Disable storage for wasm
# kotoba-storage = { workspace = true, optional = true, default-features = false }
# kotoba-jsonnet = { workspace = true, optional = true, default-features = false }


[dev-dependencies]
tempfile = "3.0"
