[package]
name = "kotoba-state-graph"
version = "0.1.0"
edition = "2021"
description = "UI state management library for Kotoba using graph rewrite rules."
authors = ["jun784"]
license = "MIT OR Apache-2.0"

[dependencies]
# Dependencies will be added from the main kotoba crate
# kotoba-core = { path = "../../" } # This will be tricky, need to figure out deps
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
