[package]
name = "kotoba-ocel"
version = "0.1.22"
edition = "2021"
description = "OCEL v2 (Object-Centric Event Log) implementation for KotobaDB"
license = "MIT OR Apache-2.0"

[dependencies]
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "1.3"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Collections and utilities
indexmap = { version = "2.0", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Kotoba ecosystem
kotoba-graph-core = { path = "../../010-core/016-kotoba-graph-core" }
kotoba-errors = { path = "../../010-core/011-kotoba-errors" }
kotoba-types = { path = "../../010-core/011-kotoba-types" }
kotoba-cid = { path = "../../010-core/013-kotoba-cid" }
kotoba-auth = { path = "../../010-core/016-kotoba-auth" }
