[package]
name = "kotoba-ocel"
version = "0.1.22"
edition = "2021"
description = "OCEL v2 (Object-Centric Event Log) implementation for KotobaDB"
license = "MIT OR Apache-2.0"

[dependencies]
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "1.3"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Collections and utilities
indexmap = { version = "2.0", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Kotoba types
kotoba-core = { path = "../012-kotoba-core", version = "0.1.22" } # Still needed for core logic
kotoba-types = { path = "../010-kotoba-types" } # Explicit dependency on types
kotoba-auth = { path = "../016-kotoba-auth" } # For SecureResource trait
kotoba-errors = "0.1.2"
kotoba-schema = { path = "../014-kotoba-schema", version = "0.1.22" }
kotoba-cid = { path = "../013-kotoba-cid", version = "0.1.22" }
