[package]
name = "kotoba-server-workflow"
version = "0.1.0"
edition = "2021"
description = "Workflow integration for Kotoba HTTP server"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
homepage = "https://github.com/com-junkawasaki/kotoba"
keywords = ["workflow", "http", "server", "integration"]
categories = ["web-programming::http-server", "development-tools"]

[dependencies]
# Core server functionality
kotoba-server-core = { path = "../kotoba-server-core", version = "0.1.0" }

# Workflow engine - minimal core interface
kotoba-workflow-core = { path = "../kotoba-workflow-core", version = "0.1.0", optional = true }

# Axum for HTTP server integration
axum = { version = "0.7", features = ["json", "macros"] }

# JSON and serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Async traits
async-trait = "0.1"

# Logging
tracing.workspace = true

# Date/time handling
chrono.workspace = true

# Kotoba crates
kotoba-errors.workspace = true

[features]
default = ["workflow"]
workflow = ["dep:kotoba-workflow-core"]
