[package]
name = "kotoba-workflow-activities"
version = "0.1.0"
edition = "2021"
description = "Pre-built activity libraries for Kotoba Workflow Engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kotoba/kotoba"
homepage = "https://github.com/kotoba/kotoba"

[dependencies]
kotoba-workflow = { path = "../kotoba-workflow", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"], optional = true }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "mysql", "sqlite"], optional = true }
redis = { version = "0.23", optional = true }
lapin = { version = "2.1", optional = true }
aws-sdk-s3 = { version = "0.28", optional = true }
aws-config = { version = "0.57", optional = true }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.5"
base64 = "0.21"
url = "2.3"
lettre = { version = "0.10", features = ["tokio1-native-tls"], optional = true }
csv = { version = "1.1", optional = true }
zip = { version = "0.6", optional = true }
tempfile = { version = "3.3", optional = true }
mime_guess = { version = "2.0", optional = true }

[features]
default = ["http", "database", "cache", "messaging"]
http = ["reqwest"]
database = ["sqlx"]
cache = ["redis"]
messaging = ["lapin"]
cloud = ["aws-sdk-s3", "aws-config"]
email = ["lettre"]
file = ["zip", "csv", "mime_guess"]
