[package]
name = "kotoba-memory"
version = "0.1.16"
edition = "2021"
description = "Advanced memory management and optimization tools for KotobaDB"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
homepage = "https://github.com/com-junkawasaki/kotoba"
keywords = ["memory", "optimization", "management", "performance"]
categories = ["development-tools", "memory-management"]
documentation = "https://docs.rs/kotoba-memory"

[dependencies]
# KotobaDB core crates
# kotoba-db-core temporarily disabled - will be replaced with kotoba-storage
kotoba-db-engine-memory = { path = "../../200-application/kotoba-db-engine-memory", version = "0.1.16" }
kotoba-db-engine-lsm = { path = "../../200-application/kotoba-db-engine-lsm", version = "0.1.16" }
kotoba-db = { path = "../../200-application/kotoba-graphdb", version = "0.1.16" }

# Profiling integration
kotoba-profiler = { path = "../../200-application/kotoba-profiler", version = "0.1.16" }

# Memory management
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
futures = "0.3"
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0"
uuid = { version = "1.18", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"

# Memory optimization
crossbeam = "0.8"
dashmap = "5.5"
lru = "0.12"

[features]
default = []
cluster = []
jemalloc = ["tikv-jemallocator"]
mimalloc = ["dep:mimalloc"]

[dependencies.tikv-jemallocator]
version = "0.5"
optional = true

[dependencies.mimalloc]
version = "0.1.38"
optional = true
