[package]
name = "kotoba-vm-cli"
version = "0.1.1"
edition = "2021"
description = "Command-line interface for the Digital Computing System VM"
license = "Apache-2.0"

[[bin]]
name = "kotoba-vm-cli"
path = "src/main.rs"

[dependencies]
kotoba-vm-core = { path = "../kotoba-vm-core" }
kotoba-vm-types = { path = "../kotoba-vm-types" }
kotoba-vm-memory = { path = "../kotoba-vm-memory" }
kotoba-vm-cpu = { path = "../kotoba-vm-cpu" }
kotoba-vm-scheduler = { path = "../kotoba-vm-scheduler" }
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
