[package]
name = "kotoba-repl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Kotoba REPL - Interactive shell for Kotoba programming language"
keywords = ["repl", "interactive", "shell", "kotoba", "programming"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
# Command line editing and history
rustyline = "12.0"
rustyline-derive = "0.8"

# Color output
colored = "2.0"

# Async runtime
tokio = { workspace = true, features = ["full"] }

# Utilities
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
toml = "0.8"

# Terminal UI
console = "0.15"
dialoguer = "0.11"
indicatif = "0.17"

# Kotoba core dependencies
kotoba-logic = { path = "../../010-core/009-kotoba-logic" }
kotoba-types = { path = "../../010-core/010-kotoba-types" }
kotoba-ir = { path = "../../010-core/011-kotoba-ir" }

# Kotoba language dependencies
kotoba-syntax = { path = "../020-kotoba-syntax" }
kotoba-parser = { path = "../021-kotoba-parser" }
kotoba-analyzer = { path = "../022-kotoba-analyzer" }
kotoba-kotobas = { path = "../023-kotoba-kotobas" }
kotoba-jsonnet = { path = "../023-kotoba-jsonnet" }
kotoba-formatter = { path = "../024-kotoba-formatter" }
kotoba-linter = { path = "../025-kotoba-linter" }
# kotoba-jsonnet = { path = "../../200-application/kotoba-jsonnet", version = "0.1.16" } # Temporarily disabled due to compilation issues

[dev-dependencies]
tokio-test = "0.4"
