[package]
name = "kotoba-bench"
version = "0.1.16"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Comprehensive benchmarking suite for KotobaDB"
keywords = ["benchmark", "performance", "testing", "database", "metrics"]
categories = ["development-tools::profiling", "database-implementations"]
documentation = "https://docs.rs/kotoba-bench"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# KotobaDB core crates - Storage layer
kotoba-core = { path = "../../000-core/kotoba-core", version = "0.1.22" }
kotoba-storage = { path = "../../100-storage/kotoba-storage", version = "0.1.22" }
# kotoba-memory = { path = "../../crates/100-storage/kotoba-memory", version = "0.1.22" }  # Temporarily disabled
kotoba-graphdb = { path = "../../100-storage/kotoba-graphdb", version = "0.1.22" }
# kotoba-db-cluster = { path = "../../100-storage/kotoba-db-cluster", version = "0.1.22", optional = true }  # Temporarily disabled

# Benchmarking utilities
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
futures = "0.3"
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0"
uuid = { version = "1.18", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
rand = { version = "0.8", features = ["small_rng"] }
hdrhistogram = "7.5"
csv = "1.1"
statrs = "0.16"
plotters = { version = "0.3", optional = true }

# System monitoring
sysinfo = "0.30"

[features]
default = []
# cluster = ["kotoba-db-cluster"]  # Temporarily disabled
visualization = ["plotters"]

[[bench]]
name = "crud_operations"
harness = false
path = "src/crud_operations.rs"

[[bench]]
name = "query_performance"
harness = false
path = "src/query_performance.rs"

[[bench]]
name = "transaction_throughput"
harness = false
path = "src/transaction_throughput.rs"

[[bench]]
name = "memory_usage"
harness = false
path = "src/memory_usage.rs"

[[bench]]
name = "storage_operations"
harness = false
path = "src/storage_operations.rs"

[[bench]]
name = "advanced_algorithms"
harness = false
path = "src/advanced_algorithms.rs"

[[bench]]
name = "jsonnet_benchmark"
harness = false
path = "src/jsonnet_benchmark.rs"

[[bench]]
name = "parallel_processing"
harness = false
path = "src/parallel_processing.rs"

[[bench]]
name = "query_execution"
harness = false
path = "src/query_execution.rs"

[[bench]]
name = "rewrite_operations"
harness = false
path = "src/rewrite_operations.rs"

[[bench]]
name = "graph_operations"
harness = false
path = "src/graph_operations.rs"


[[bin]]
name = "simple_benchmark"
path = "src/simple_benchmark.rs"

[[bin]]
name = "parallel_benchmark"
path = "src/parallel_benchmark.rs"

[[bin]]
name = "benchmark_runner"
path = "src/bin/benchmark_runner.rs"
