[package]
name = "kotoba-storage-redis"
version = "0.1.22"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Redis adapter implementation for kotoba-storage"
keywords = ["storage", "redis", "cache", "persistence", "database"]
categories = ["database-implementations", "data-structures"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-storage-redis"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# KotobaDB core crates
kotoba-storage = { path = "../kotoba-storage", version = "0.1.22" }

# Redis client
redis = { version = "0.23", features = ["tokio-comp", "cluster", "connection-manager", "tokio-native-tls-comp"] }

# Async runtime
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
async-trait = "0.1"
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Compression
lz4 = { version = "1.24", optional = true }

# Logging and metrics
tracing = "0.1"
metrics = { version = "0.21", optional = true }

# Utilities
uuid = { version = "1.18", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }

# For testing
tempfile = "3.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.0"
criterion = { version = "0.5", features = ["html_reports"] }
# kotoba-memory = { path = "../kotoba-memory", version = "0.1.22" }

[features]
default = ["compression", "metrics"]
compression = ["lz4"]
metrics = ["dep:metrics"]
cluster = []
