[package]
name = "vm_hardware"
version = "0.1.0"
edition = "2021"
description = "Heterogeneous hardware tile simulation for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "vm_hardware"
path = "src/lib.rs"

[dependencies]
vm_types = { path = "../vm-types" }
