[package]
name = "kotoba-workflow-operator"
version = "0.1.0"
edition = "2021"
description = "Kubernetes operator for Kotoba Workflow Engine"
license = "Apache-2.0"
repository = "https://github.com/kotoba/kotoba"
homepage = "https://github.com/kotoba/kotoba"

[dependencies]
kotoba-workflow = { path = "../kotoba-workflow", version = "0.1.0" }
kube = { version = "0.87", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20", features = ["v1_28"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
futures = "0.3"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"

[dev-dependencies]
kube = { version = "0.87", features = ["runtime", "derive"] }
tokio-test = "0.4"

[[bin]]
name = "controller"
path = "src/main.rs"
