[package]
name = "kotoba-language"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Unified language processing for Kotoba - integrates all language features"
keywords = ["language", "parser", "formatter", "linter", "repl"]
categories = ["development-tools", "parsing"]

[dependencies]
# Kotoba core dependencies
kotoba-logic = { path = "../../010-core/009-kotoba-logic" }
kotoba-types = { path = "../../010-core/010-kotoba-types" }
kotoba-ir = { path = "../../010-core/011-kotoba-ir" }
kotoba-rewrite-kernel = { path = "../../010-core/012-kotoba-rewrite-kernel" }
kotoba-compose = { path = "../../010-core/013-kotoba-compose" }

# Kotoba language dependencies
kotoba-syntax = { path = "../020-kotoba-syntax" }
kotoba-parser = { path = "../021-kotoba-parser" }
kotoba-analyzer = { path = "../022-kotoba-analyzer" }
kotoba-kotobas = { path = "../023-kotoba-kotobas" }
kotoba-jsonnet = { path = "../023-kotoba-jsonnet" }
kotoba-formatter = { path = "../024-kotoba-formatter" }
kotoba-linter = { path = "../025-kotoba-linter" }
kotoba-lsp = { path = "../026-kotoba-lsp" }
kotoba-repl = { path = "../027-kotoba-repl" }
kotoba2tsx = { path = "../028-kotoba2tsx" }
kotobas-wasm = { path = "../029-kotobas-wasm" }

# Standard dependencies
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }

# Note: Language feature integration will be added in future phases
# to avoid cyclic dependencies during the transition period

[features]
default = []
full = []
