[package]
name = "kotoba-vm-memory"
version = "0.1.0"
edition = "2021"
description = "Memory management system for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "kotoba_vm_memory"
path = "src/lib.rs"

[dependencies]
kotoba-vm-types = { path = "../kotoba-vm-types" }
