[package]
name = "kotoba-db-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
ciborium = "0.2"
blake3 = "1.5"
async-trait = "0.1"

kotoba-core = { path = "../kotoba-core" }
kotoba-cid = { path = "../kotoba-cid" }
