[package]
name = "kotoba-state-graph"
version = "0.1.16"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "UI state management library for Kotoba using graph rewrite rules."
keywords = ["state", "ui", "graph", "rewrite", "frontend"]
categories = ["gui", "data-structures"]
documentation = "https://docs.rs/kotoba-state-graph"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }

# Kotoba dependencies - Port layer
kotoba-storage = { path = "../../100-storage/kotoba-storage" }
kotoba-core = { path = "../../000-core/kotoba-core" }
kotoba-errors = { path = "../../000-core/kotoba-errors" }
