[package]
name = "kotoba-deploy-controller"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Deployment controller for Kotoba deployment system"
keywords = ["deployment", "controller", "orchestration", "kubernetes", "docker"]
categories = ["concurrency", "algorithms", "development-tools"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-deploy-controller"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Kotoba dependencies
kotoba-core = { workspace = true }
kotoba-graph = { workspace = true }
kotoba-execution = { workspace = true }
kotoba-rewrite = { workspace = true }
kotoba-deploy-core = { path = "../../200-application/kotoba-deploy-core", version = "0.1.15" }
kotoba-deploy-scaling = { path = "../../200-application/kotoba-deploy-scaling", version = "0.1.15" }
kotoba-deploy-network = { path = "../../200-application/kotoba-deploy-network", version = "0.1.15" }
kotoba-deploy-git = { path = "../../200-application/kotoba-deploy-git", version = "0.1.15" }

# Common dependencies
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }

# HTTP client for health checks
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }

# Cron scheduling
cron = "0.12"

# Concurrent collections
dashmap = "5.5"

# URL encoding
percent-encoding = "2.3"

# Async utilities
futures.workspace = true

# Utilities
tempfile.workspace = true
