[package]
name = "kotobas-wasm"
version = "0.1.16"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WASM bindings for the KotobaScript compiler"
keywords = ["wasm", "webassembly", "compiler", "kotoba", "javascript"]
categories = ["wasm", "compilers"]
documentation = "https://docs.rs/kotobas-wasm"
homepage = "https://github.com/com-junkawasaki/kotoba"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wee_alloc = { version = "0.4.5", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
tracing = "0.1"
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
uuid = { workspace = true, features = ["v4", "serde", "js"] }
once_cell = "1.0"

# Kotoba core dependencies
kotoba-logic = { path = "../../010-core/009-kotoba-logic" }
kotoba-types = { path = "../../010-core/010-kotoba-types" }
kotoba-ir = { path = "../../010-core/011-kotoba-ir" }
kotoba-rewrite-kernel = { path = "../../010-core/012-kotoba-rewrite-kernel" }

# Kotoba language dependencies
kotoba-kotobas = { path = "../023-kotoba-kotobas" }
# kotoba-storage = { path = "../../030-storage/031-kotoba-storage" } # Temporarily disabled

# TODO: Replace with KeyValueStore-based workflow
# kotoba-workflow = { path = "../../300-workflow/kotoba-workflow", default-features = false, features = ["wasm-bindgen"] }

[features]
default = ["console_error_panic_hook"]
