[package]
name = "kotoba-projection-engine"
version = "0.1.0"
edition = "2021"
description = "Real-time projection engine for GraphDB materialization using RocksDB"
license = "MIT OR Apache-2.0"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Collections and utilities
dashmap = "5.5"
itertools = "0.12"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Futures for async processing
futures = "0.3"

# Metrics
metrics = "0.23"

# Kotoba dependencies - Port layer
kotoba-storage = { path = "../../100-storage/kotoba-storage" }
kotoba-event-stream = { path = "../../200-application/kotoba-event-stream" }
kotoba-ocel = { path = "../../000-core/kotoba-ocel" }
