[package]
name = "kotoba-monitoring"
version = "0.1.21"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Comprehensive monitoring and metrics collection system for KotobaDB"
keywords = ["monitoring", "metrics", "prometheus", "health-check", "observability"]
categories = ["development-tools::profiling", "database-implementations"]
documentation = "https://docs.rs/kotoba-monitoring"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
parking_lot = "0.12"

# KotobaDB dependencies
kotoba-graphdb = "0.1.21"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
