[package]
name = "kotoba-rewrite"
version = "0.1.2"
edition = "2021"
description = "Kotoba Rewrite Components"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jun784/kotoba"


authors = ["Jun Kawasaki <jun784@example.com>"]
keywords = ["rewrite", "graph-transformation", "dpo"]
categories = ["algorithms", "database-implementations"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-rewrite"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
uuid = { workspace = true, features = ["v4"] }
kotoba-core = { path = "../kotoba-core", version = "0.1.1" }
kotoba-graph = { path = "../kotoba-graph", version = "0.1.1" }
kotoba-storage = { path = "../kotoba-storage", version = "0.1.1" }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
