[package]
name = "kotoba-profiler"
version = "0.1.21"
edition = "2021"
description = "Advanced profiling and performance analysis tools for KotobaDB"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
homepage = "https://github.com/com-junkawasaki/kotoba"
keywords = ["profiling", "performance", "benchmarking", "analysis"]
categories = ["development-tools::profiling", "database-implementations"]
documentation = "https://docs.rs/kotoba-profiler"

[dependencies]
# KotobaDB core crates
kotoba-storage = "0.1.22"
kotoba-graphdb = "0.1.21"

# Benchmarking integration
# kotoba-bench temporarily disabled - will be re-enabled when available

# Profiling and monitoring
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
futures = "0.3"
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.0"
uuid = { version = "1.18", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"

# System profiling
sysinfo = "0.30"
pprof = { version = "0.13", features = ["protobuf"], optional = true }
prost = { version = "0.12", optional = true }

# Performance analysis
statrs = "0.16"
hdrhistogram = "7.5"
plotters = { version = "0.3", optional = true }

[features]
default = []
cluster = []
visualization = ["plotters"]
flamegraph = ["pprof"]

[[bin]]
name = "kotoba-profiler"
path = "src/main.rs"
