[package]
name = "vm_types"
version = "0.1.0"
edition = "2021"
description = "Shared type definitions for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "vm_types"
path = "src/lib.rs"

[dependencies]
