[package]
name = "kotoba-projection-engine"
version = "0.1.0"
edition = "2021"
description = "Real-time projection engine for GraphDB materialization using RocksDB"
license = "MIT OR Apache-2.0"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# RocksDB for persistent storage
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Collections and utilities
dashmap = "5.5"
itertools = "0.12"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Futures for async processing
futures = "0.3"

# Metrics
metrics = "0.23"

# Placeholder for Kotoba dependencies
# kotoba-event-stream = { path = "../kotoba-event-stream" }
# kotoba-cache = { path = "../kotoba-cache" }
# kotoba-graph-projection = { path = "../kotoba-graph-projection" }
