[package]
name = "vm_memory"
version = "0.1.0"
edition = "2021"
description = "Memory management system for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "vm_memory"
path = "src/lib.rs"

[dependencies]
vm_types = { path = "../vm-types" }
