[package]
name = "kotoba-ir"
version = "0.1.22"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kotoba-rewrite-kernel = { path = "../012-kotoba-rewrite-kernel" }
