[build]
target-dir = ".target"
rustflags = [
  "-C", "target-cpu=native"
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[profile.dev]
incremental = true
codegen-units = 16

[profile.release]
incremental = false
lto = "thin"
codegen-units = 8
