[package]
name = "kotoba-formatter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Kotoba Code Formatter - Formats .kotoba files with consistent style"
keywords = ["formatter", "code", "style", "kotoba", "dsl"]
categories = ["development-tools", "text-processing"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
futures = "0.3"
async-trait = "0.1"
parking_lot = "0.12"
dirs = { workspace = true }
toml = "0.8"

# Kotoba core dependencies
kotoba-logic = { path = "../../010-core/009-kotoba-logic" }
kotoba-types = { path = "../../010-core/010-kotoba-types" }
kotoba-ir = { path = "../../010-core/011-kotoba-ir" }

# Kotoba language dependencies
kotoba-parser = { path = "../021-kotoba-parser" }
kotoba-syntax = { path = "../020-kotoba-syntax" }
# kotoba-jsonnet = { path = "../../200-application/kotoba-jsonnet", version = "0.1.16" } # Temporarily disabled due to compilation issues

[dev-dependencies]
tokio-test = "0.4"
