[package]
name = "kotoba-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Advanced persistent storage layer with MVCC, LSM-Tree, and Merkle DAG"
keywords = ["storage", "persistence", "mvcc", "merkle", "database"]
categories = ["database-implementations", "data-structures", "cryptography"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-storage"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde = { workspace = true, features = ['derive'] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
parking_lot = "0.12"
sha2 = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
hex = { workspace = true }
rocksdb = { version = "0.21", optional = true }
tempfile = "3.0"
async-trait = "0.1"
redis = { version = "0.23", features = ["tokio-comp", "connection-manager"] }
tokio = { version = "1.0", features = ["sync", "rt"] }
kotoba-core = { workspace = true }
kotoba-errors = { path = "../kotoba-errors" }
kotoba-graph = { workspace = true }
kotoba-cid = { path = "../kotoba-cid" }

[features]
default = []
rocksdb = ["dep:rocksdb"]
object_storage = []

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
