[package]
name = "kotoba-storage-rocksdb"
version = "0.1.22"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "RocksDB implementation for Kotoba storage interface"
keywords = ["storage", "database", "rocksdb"]
categories = ["database"]

[dependencies]
kotoba-core = { path = "../../010-core/012-kotoba-core" }
kotoba-storage = { path = "../031-kotoba-storage" }
rocksdb = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
