[package]
name = "kotoba-graphdb"
version = "0.1.22"
edition = "2021"
description = "RocksDB-based Graph Database for KotobaDB"
license = "MIT OR Apache-2.0"

[dependencies]
# RocksDB for persistent storage
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Collections and utilities
dashmap = "5.5"
itertools = "0.12"
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Futures for async processing
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Metrics
metrics = "0.23"

# Kotoba dependencies
kotoba-core = { path = "../../000-core/kotoba-core", version = "0.1.22" }
kotoba-errors = "0.1.2"
kotoba-ocel = "0.1.22"
