[package]
name = "kotoba-cli"
version = "0.1.21"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Command Line Interface for Kotoba graph processing system"
keywords = ["cli", "command-line", "graph", "processing", "tool"]
categories = ["command-line-utilities", "development-tools"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-cli"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Core dependencies
kotoba-core = { path = "../../000-core/kotoba-core" }
kotoba-errors = { path = "../../000-core/kotoba-errors" }
# kotoba-jsonnet removed - functionality moved to kotoba-kotobas

# Optional features (temporarily disabled to focus on core functionality)
# kotoba-graph = "0.1.21"
# kotoba-execution = "0.1.21"
# kotoba-rewrite = "0.1.21"
# kotoba-storage = "0.1.21"

# CLI framework
clap = { version = "4.0", features = ["derive"] }

# Async runtime
tokio = { version = "1.0", features = ["full"] }

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# File system
tokio-util = { version = "0.7", features = ["io"] }

# Configuration
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"
dirs = "5.0"
regex = "1.10"

# Terminal UI
console = "0.15"
dialoguer = "0.11"

[[bin]]
name = "kotoba"
path = "src/main.rs"
