[package]
name = "kotoba-package-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Kotoba Package Manager - Dependency management and package distribution"
keywords = ["package-manager", "dependency", "registry", "kotoba"]
categories = ["development-tools", "command-line-utilities"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
urlencoding = "2.1"
anyhow = { workspace = true }
async-trait = "0.1"
futures = { workspace = true }
parking_lot = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
semver = "1.0"
sha2 = { workspace = true }
hex = { workspace = true }
toml = "0.8"
dirs = { workspace = true }
walkdir = "2.0"
tempfile = "3.0"

# Kotoba ecosystem
kotoba-core = { path = "../kotoba-core", version = "0.1.17" }

[dev-dependencies]
tokio-test = "0.4"
