[package]
name = "kotoba-vm-core"
version = "0.1.0"
edition = "2021"
description = "Core VM integration layer for the Digital Computing System VM"
license = "Apache-2.0"

[lib]
name = "kotoba_vm_core"
path = "src/lib.rs"

[dependencies]
kotoba-vm-types = { path = "../kotoba-vm-types" }
kotoba-vm-memory = { path = "../kotoba-vm-memory" }
kotoba-vm-cpu = { path = "../kotoba-vm-cpu" }
kotoba-vm-scheduler = { path = "../kotoba-vm-scheduler" }
kotoba-vm-hardware = { path = "../kotoba-vm-hardware" }
kotoba-vm-gnn = { path = "../kotoba-vm-gnn" }
serde_json = "1.0"
tokio = { workspace = true }
