apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kotoba.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kotoba.labels" . | nindent 4 }}
data:
  # Kotoba configuration in Jsonnet format
  kotoba-config.jsonnet: |
{{ include "kotoba.clusterConfig" . | indent 4 }}
