[package]
name = "kotoba-workflow-core"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Core workflow engine for Kotoba - minimal interface without heavy dependencies"
homepage = "https://github.com/com-junkawasaki/kotoba"
keywords = ["workflow", "automation", "orchestration", "core"]
categories = ["development-tools", "api-bindings"]

[dependencies]
# Kotoba core types only - minimal dependencies
kotoba-core.workspace = true
kotoba-errors.workspace = true

# Common dependencies (minimal set)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
thiserror = "2.0"
anyhow = "1.0"

# Async traits
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
tempfile.workspace = true
