[package]
name = "kotoba-ocel"
version = "0.1.0"
edition = "2021"
description = "OCEL v2 (Object-Centric Event Log) implementation for KotobaDB"
license = "MIT OR Apache-2.0"

[dependencies]
# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "1.3"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Collections and utilities
indexmap = "2.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
regex = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"

# Kotoba types
kotoba-types = { path = "../kotoba-core" }
kotoba-errors = { path = "../kotoba-errors" }
