[package]
name = "kotoba-analyzer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Semantic Analyzer for the Kotoba language, performing type checking and producing IR."

[dependencies]
kotoba-syntax = { path = "../020-kotoba-syntax" }
kotoba-parser = { path = "../021-kotoba-parser" }
kotoba-core = { path = "../../010-core/012-kotoba-core" }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
