[package]
name = "kotoba-logic"
version = "0.1.22"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Core data structures and algorithms for the Kotoba distributed graph database system"
keywords = ["graph", "database", "gql", "rewrite", "types"]
categories = ["data-structures", "algorithms"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-core"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
kotoba-types = { path = "../011-kotoba-types" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
sha2 = "0.10"
hex = "0.4"
parking_lot = "0.12"
rand = "0.8"

# Kotoba ecosystem
# kotoba-graph = "0.1.16" # Temporarily removed to break circular dependency
# kotoba-security = { path = "../../200-application/kotoba-security", optional = true } # Temporarily disabled due to circular dependency

# Schema validation
schemars = { version = "0.8", optional = true }
jsonschema = "0.17"

# Regular expressions
regex = "1.10"

# Additional hash functions
blake3 = "1.8"

[features]
default = ["std", "schemars"]
std = []
wasm = ["wasm-bindgen", "web-sys", "js-sys"]
schemars = ["dep:schemars"]
# security = ["dep:kotoba-security"] # Temporarily disabled due to circular dependency
# Placeholder feature for future use
security = []

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
