[package]
name = "kotoba2tsx"
version = "0.1.0"
edition = "2021"
description = "Kotoba to TSX converter - Convert .kotoba configuration files to React TSX components"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jun784/kotoba"
authors = ["Jun Kawasaki <jun784@example.com>"]
keywords = ["react", "tsx", "converter", "jsonnet", "frontend"]
categories = ["command-line-utilities", "web-programming"]
readme = "README.md"
documentation = "https://docs.rs/kotoba2tsx"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"], optional = true }
tokio = { version = "1.0", features = ["full"] }
regex = "1.10"
jsonnet-rs = "0.17"
uuid = { workspace = true, features = ["v4"] }
parking_lot = "0.12"
hex = { workspace = true }
sha2 = { workspace = true }

# SWC integration for enhanced code generation
swc_core = { version = "0.90", features = ["ecma_codegen", "ecma_parser", "ecma_transforms", "ecma_visit", "common"] }
swc_ecma_codegen = "0.146"
swc_ecma_parser = "0.141"
swc_ecma_transforms = "0.226"
swc_ecma_visit = "0.96"

# Lightning CSS for CSS processing and optimization
lightningcss = "1.0"

# Additional dependencies for CSS-in-JS and enhanced functionality
phf = { version = "0.11", features = ["macros"] }
indexmap = "2.0"
cssparser = "0.31"
selectors = "0.25"

[features]
default = ["std", "cli"]
std = []
cli = ["clap"]
wasm = ["wasm-bindgen", "web-sys", "js-sys"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
