[package]
name = "kotoba-config"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Dynamic configuration management system for runtime config updates"
keywords = ["configuration", "config", "management", "runtime", "hot-reload"]
categories = ["config", "filesystem"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-config"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
serde = { workspace = true, features = ['derive'] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2.0"
chrono = { workspace = true, features = ["serde"] }
futures = "0.3"
parking_lot = "0.12"
uuid = { workspace = true, features = ["v4"] }
regex = "1.0"
lazy_static = "1.4"
notify = "6.0"  # For file watching
dotenvy = "0.15" # For environment variables

# KotobaDB dependencies
kotoba-db = { path = "../kotoba-db", version = "0.1.0" }
kotoba-storage = { path = "../kotoba-storage", version = "0.1.16" }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"
