[package]
name = "kotoba-ssg"
version = "0.1.16"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Static Site Generator implemented in Kotoba language"
keywords = ["ssg", "static", "generator", "markdown", "html"]
categories = ["web-programming", "text-processing", "development-tools"]
documentation = "https://docs.rs/kotoba-ssg"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Kotoba core dependencies
kotoba-core = { path = "../kotoba-core", version = "0.1.19" }
kotoba-jsonnet = { path = "../kotoba-jsonnet", version = "0.1.17" }
kotoba-kotobas = { path = "../kotoba-kotobas", version = "0.1.16" }
kotoba-docs = { path = "../kotoba-docs", version = "0.1.16" }

# External dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
regex = "1.10"
pulldown-cmark = "0.9"
tera = "1.19"
walkdir = "2"
fs_extra = "1.3"
git2 = "0.18"
reqwest = { version = "0.11", features = ["json"] }
url = "2.4"
mime_guess = "2.0"

[dev-dependencies]
tempfile = "3.8"
assert_fs = "1.0"

[features]
default = []
full = []
