[package]
name = "kotoba-ssg"
version = "0.1.0"
edition = "2021"
description = "Static Site Generator implemented in Kotoba language"
authors = ["Kotoba Team"]
license = "MIT OR Apache-2.0"

[dependencies]
# Kotoba core dependencies
kotoba-core = { path = "../kotoba-core" }
kotoba-jsonnet = { path = "../kotoba-jsonnet" }
kotoba-kotobas = { path = "../kotoba-kotobas" }
kotoba-docs = { path = "../kotoba-docs" }

# External dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
regex = "1.10"
pulldown-cmark = "0.9"
tera = "1.19"
walkdir = "2"
fs_extra = "1.3"
git2 = "0.18"
reqwest = { version = "0.11", features = ["json"] }
url = "2.4"
mime_guess = "2.0"

[dev-dependencies]
tempfile = "3.8"
assert_fs = "1.0"

[features]
default = []
full = []
