title: Kotoba - Graph Processing System
description: A comprehensive graph processing platform featuring complete Jsonnet implementation, ISO GQL-compliant queries, and distributed execution
url: https://jun784.github.io
baseurl: /kotoba
repository: jun784/kotoba

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/

# Include files
include:
  - _pages

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
