[package]
name = "kotoba-distributed"
version = "0.1.22"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Distributed execution engine for Kotoba graph processing system"
keywords = ["distributed", "graph", "processing", "tokio", "cluster"]
categories = ["concurrency", "network-programming", "data-structures"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-distributed"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Kotoba ecosystem
kotoba-core = { path = "../../000-core/kotoba-core", version = "0.1.22" }
kotoba-errors = { path = "../../000-core/kotoba-errors", version = "0.1.2" }
kotoba-execution = { path = "../../200-application/kotoba-execution", version = "0.1.21" }
kotoba-rewrite = { path = "../../200-application/kotoba-rewrite", version = "0.1.21" }
kotoba-cid = { path = "../../000-core/kotoba-cid", version = "0.1.21" }

# Async runtime
tokio = { version = "1.0", features = ["sync", "rt", "macros"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# UUID generation
uuid = { version = "1.0", features = ["v4"] }

# Logging
tracing = "0.1"

# Error handling
thiserror = "2.0"
anyhow = "1.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4"
