[package]
name = "kotoba-linter"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Kotoba Code Linter - Static analysis tool for .kotoba files"
keywords = ["linter", "static-analysis", "code-quality", "kotoba", "diagnostics"]
categories = ["development-tools", "command-line-utilities"]

[[bin]]
name = "kotoba-lint"
path = "src/main.rs"

[dependencies]
kotoba-types = { path = "../../010-core/010-kotoba-types" }
kotoba-rewrite-kernel = { path = "../../010-core/012-kotoba-rewrite-kernel" }
kotoba-graph-core = { path = "../../010-core/016-kotoba-graph-core" }
thiserror = { workspace = true }
anyhow = "1.0"
serde = { workspace = true }
serde_json = "1.0"
regex = "1.0"
tracing = "0.1"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-lsp = "0.20"
dashmap = "5.5"
url = "2.5"
ropey = "1.6"
glob = "0.3"

[dev-dependencies]
tokio-test = "0.4"
