[package]
name = "kotoba-deploy-core"
version = "0.1.21"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/com-junkawasaki/kotoba"
description = "Core types and configuration for Kotoba deployment system"
keywords = ["deployment", "config", "types", "core"]
categories = ["data-structures", "config"]
documentation = "https://docs.rs/kotoba-deploy-core"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Kotoba core dependencies
kotoba-core = "0.1.22"
kotoba-errors = "0.1.2"

# Common dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"
sha2 = { version = "0.10", features = ["std"] }
hex = "0.4"
regex = "1.0"
tempfile = "3.0"
url = "2.0"
