[package]
name = "kotobas-wasm"
version = "0.1.16"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WASM bindings for the KotobaScript compiler"
keywords = ["wasm", "webassembly", "compiler", "kotoba", "javascript"]
categories = ["wasm", "compilers"]
documentation = "https://docs.rs/kotobas-wasm"
homepage = "https://github.com/com-junkawasaki/kotoba"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wee_alloc = { version = "0.4.5", optional = true }
serde = "1.0"
serde-wasm-bindgen = "0.6"
kotoba-workflow = { path = "../../crates/kotoba-workflow", default-features = false, features = ["wasm-bindgen"] }
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen-futures = "0.4"
uuid = { version = "1.0", features = ["v4", "serde", "js"] }

[features]
default = ["console_error_panic_hook"]
