[package]
name = "kotoba-deploy-git"
version = "0.1.21"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Git integration for Kotoba deployment system"
keywords = ["git", "github", "deployment", "webhook", "ci-cd"]
categories = ["development-tools", "api-bindings"]
readme = "README.md"
documentation = "https://docs.rs/kotoba-deploy-git"
homepage = "https://github.com/com-junkawasaki/kotoba"

[dependencies]
# Kotoba dependencies
kotoba-core = { workspace = true }
kotoba-deploy-core = { path = "../kotoba-deploy-core", version = "0.1.21" }

# Common dependencies
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
uuid.workspace = true
chrono.workspace = true
regex.workspace = true
tempfile.workspace = true

# HTTP client for GitHub API
reqwest = { version = "0.11", features = ["json"] }

# Crypto for webhook verification
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
base64.workspace = true
