[package]
name = "kotoba-schema"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Graph Schema Definition and Validation for Kotoba"
keywords = ["graph", "schema", "validation", "gql", "database"]
categories = ["data-structures", "algorithms"]
documentation = "https://docs.rs/kotoba-schema"
homepage = "https://github.com/jun784/kotoba"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
anyhow = "1.0"
regex = "1.0"

# Kotoba ecosystem
kotoba-core = { path = "../kotoba-core", version = "0.1.19" }
# kotoba-errors removed - use through kotoba-core
kotoba-graph = { path = "../kotoba-graph", version = "0.1.17", optional = true }

# Schema validation
schemars = { version = "0.8", features = ["derive"] }
jsonschema = "0.17"

# Optional async support
tokio = { version = "1.0", optional = true }

[features]
default = ["std"]
std = []
graph = ["dep:kotoba-graph"]
async = ["tokio"]

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.0"
