name: Deploy Documentation (Legacy - Replaced by static.yml)

on:
  # This workflow is replaced by static.yml
  # Keeping for reference but disabled
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
    - name: Deprecated Workflow Notice
      run: |
        echo "⚠️  This workflow (deploy-docs.yml) has been replaced by static.yml"
        echo "📝 The new workflow uses the Kotoba SSG system instead of Jekyll"
        echo "🔄 Documentation deployment is now handled by: .github/workflows/static.yml"
        echo ""
        echo "This workflow file is kept for reference but is no longer active."
        echo "Please use 'static.yml' for documentation deployment."
