name: Nix Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enable flakes
      run: |
        mkdir -p ~/.config/nix
        echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf

    - name: Cache Nix store
      uses: cachix/cachix-action@v15
      with:
        name: kotoba
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      continue-on-error: true

    - name: Build Kotoba with Nix
      run: |
        nix build .#default

    - name: Run tests in Nix environment
      run: |
        nix develop --command 'cargo test --workspace'

    - name: Build Docker image with Nix
      run: |
        nix build .#dockerImage
        docker load < result

    - name: Verify Docker image
      run: |
        docker images kotoba:latest

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kotoba-binary
        path: result/bin/kotoba

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enable flakes
      run: |
        mkdir -p ~/.config/nix
        echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf

    - name: Build Kotoba with Nix (macOS)
      run: |
        nix build .#default

    - name: Run tests in Nix environment (macOS)
      run: |
        nix develop --command 'cargo test --workspace --lib'  # Skip integration tests on macOS
